package edu.poly.common;

public enum PageType {
	USER_MANAGEMENT_PAGE,
	REPORT_MANAGEMENT_PAGE,
	VIDEO_MANAGEMEMT_PAGE,
	SITE_HOME_PAGE,
	SITE_LOGIN_PAGE,
	SITE_REGISTATION_PAGE,
	SITE_CHANGE_PASSWORD_PAGE,
	SITE_EDIT_PROFILE_PAGE,
	SITE_FORGOT_PASSWAORD_PAGE,
	SITE_VIDEO_DETAIL_PAGE,
	SITE_FAVORITES_PAGE,
	SITE_SHARE_PAGE
}
